### ISSUE TITLE
Implement the blacklist (or whitelist) parameter in Hill Climbing Search

### ISSUE THREAD

**Issue by Blaieet** [erdogant/bnlearn#1]
Hi!
First of all, thank you for exporting bnlearn to python!

I'm currently developing my bachelor's thesis project calling the bnlearn package with rpy2. Specifically, I call the `hc` function with his `blacklist` parameter and collect the results back to python. On account of that, the overall perfomance reduces significantly. 

So, if you're willing to, I would love this `blackllist` parameter in the `hc` function. 

Regards.

**Comment by erdogant** [comment]
Hi Blaieet, Its great to hear that this package helpful to you!
I noticed that the blacklist/whitelist parameters are not available in the current v.0.1.9 but only in the git repo. Nevertheless, I did add this functionality the hc function but it only works if you use a version newer then  v.0.1.9 (such as v.0.1.9.dev).

**Comment by Blaieet** [comment]
I see. Thank you so much for your time!
