### ISSUE TITLE
Dynamic Bayesian Network support?

### ISSUE THREAD

**Issue by nivmorabin** [erdogant/bnlearn#100]
Hi,

Are there any plans for supporting a Dynamic Bayesian Network?

There's a pgmpy module (https://pgmpy.org/models/dbn.html) but it's not nearly as intuitive to use as bnlearn :)

Thanks In advance.

**Comment by erdogant** [comment]
Hi @nivmorabin thanks for the feedback! But at the moment not direct plans but it is already in Pgmpy, so this gives opportunities.

**Comment by erdogant** [comment]
I added the DBN functionality! Dynamic Bayesian Network (DBN) implemented. https://github.com/erdogant/bnlearn/issues/100. See docs [here](https://erdogant.github.io/bnlearn/pages/html/bnlearn.bnlearn.html#bnlearn.bnlearn.make_DAG) and [here](https://erdogant.github.io/bnlearn/pages/html/bnlearn.parameter_learning.html#module-bnlearn.parameter_learning).
Update to the latest version.

`pip install -U bnlearn`

**Comment by nivmorabin** [comment]
Fantastic @erdogant! thank you!
