### ISSUE TITLE
What kind of data type does the library handle?

### ISSUE THREAD

**Issue by akshatakarjun** [erdogant/bnlearn#101]
Hi, 

Thank you for this fantastic library. 

I was just wondering what datatype data does the library handle? Because I have a dataset with variables (features) that has both continuous and discrete values in it. And the model is not giving a satisfactory answer. 

Also, Is this built on top of PgmPy? 

Looking forward to the answer as early as possibe.

**Comment by erdogant** [comment]
Hi @akshatakarjun thank you for your message.

Bnlearn can handle discrete data. If you have both continuous and discrete data, you have a few options. You can discretize your continuous values based on domain knowledge or other expertise, or you can use the continuous data approach. However, the latter requires some knowledge of the data structure (the edges). There is quite some information on the documentation pages over [here](https://erdogant.github.io/bnlearn/pages/html/Continuous%20Data.html)

**Comment by erdogant** [comment]
See also #94

**Comment by akshatakarjun** [comment]
Thank you. 

The documentation was very helpful. I have a couple more questions, 

1. Is this built on top of Pgmpy? 

2. I read previous threads about the bnlearn library handling missing values. However, I am still confused and posting it here, Does the library handle missing values? 

3. What is the minimum number of samples/data points required for the library to work efficiently? I have been researching on applying PGMs for small datasets.

**Comment by erdogant** [comment]
This package is indeed built on top of pgmpy, but many custom functionalities are added to bnlearn over time. Handling missing values depends on the type of analysis you aim to do. Look [here](https://pgmpy.org/search.html?q=missing+values) for more information. The minimum and max. number of samples also depends on the method and approach you aim to approach. The data does not need to be encoded. I recommend looking into the [documentation pages](https://erdogant.github.io/bnlearn/).

**Comment by erdogant** [comment]
I added functionality to impute data in case you have missing values. See docs [here](https://erdogant.github.io/bnlearn/pages/html/impute.html).
Update to the latest version.

`pip install -U bnlearn`

**Comment by erdogant** [comment]
If there are any other questions regarding this subject, re-open if needed.
