### ISSUE TITLE
Does bnlearn support Distributed computing?

### ISSUE THREAD

**Issue by Subbui** [erdogant/bnlearn#11]
I really appreciate for crating this library. Thanks. Does bnlearn support the distributed computing? also could you share if you have a comparison doc for R vs Python version of bnlearn package?

**Comment by erdogant** [comment]
Thank you for your message! Very appreciated. But unfortunately no distr.computing. I also do not have a comparison documentation. I do have documentation for bnlearn! https://erdogant.github.io/bnlearn

**Comment by Subbui** [comment]
Thanks for your quick response. Sure. I'm referring the documentation. Thanks
