### ISSUE TITLE
Can I create a customer structure with bnlearn?

### ISSUE THREAD

**Issue by Subbui** [erdogant/bnlearn#12]
Hi, I'm trying to build a network structure of my own and I couldn't find an option to do so. I could learn the structure from the data by structure_learning.fit method, but is there a way I can create my own structure with bnlearn? I could do it pgmpy, but wanted to check if there is an option in bnlearn as well. Thanks

**Comment by erdogant** [comment]
Yes, this is possible. There are different ways to approach this, depending on your end goal and starting point.

If your starting point is that you have the data and know the DAG, look here:

Link:
https://erdogant.github.io/bnlearn/pages/html/UseCases.html

Go to the section:
“Make inferences when you have data and know-how”

**Comment by Subbui** [comment]
Awesome. thanks for pointing me to the exact solution.

**Comment by erdogant** [comment]
Nice. Have fun!
