### ISSUE TITLE
issue with the network hailfinder and water

### ISSUE THREAD

**Issue by MingjiaLi666** [erdogant/bnlearn#13]
when trying to use bnlearn.sample from the BN 'water' it comes with ValueError: probabilities do not sum to 1
when trying to import the BN 'hailfinder' it comes with ValueError: probabilities do not sum to 1
'water.bif' and 'hailfinder.bif' are both downloaded from https://www.bnlearn.com/bnrepository/

**Comment by erdogant** [comment]
I updated the library with a check for CPDs. Incorrect CPDs will be printed.
It appears that water contains a CPD (CKNI_12_00) that has the value [0.3333, 0.3333, 0.3333] and does not add up exactly to 1.
When you manually change it into the following it works:

probability ( CKNI_12_00 ) {
  table 0.3333333, 0.3333333, 0.3333334;
}

The hailfinder contains many other inconsistencies in the structure. You need to fix these manually if you want to use it.

Update bnlearn with the following. The version should be >= 0.3.10

`pip install -U bnlearn`

**Comment by MingjiaLi666** [comment]
thx
