### ISSUE TITLE
cannot import name 'ConstraintBasedEstimator' from 'pgmpy.estimators'

### ISSUE THREAD

**Issue by jmagosta** [erdogant/bnlearn#15]
`import bnlearn` fails due to a modification in pgmpy, version 0.1.12:

```
  Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import bnlearn
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Users\joagosta\AppData\Local\Programs\Python\Python38\lib\site-packages\bnlearn\__init__.py", line 17, in <module>
      import bnlearn.structure_learning as structure_learning
    File "C:\Users\joagosta\AppData\Local\Programs\Python\Python38\lib\site-packages\bnlearn\structure_learning.py", line 17, in <module>
      from pgmpy.estimators import ConstraintBasedEstimator
  ImportError: cannot import name 'ConstraintBasedEstimator' from 'pgmpy.estimators' (C:\Users\joagosta\AppData\Local\Programs\Python\Python38\lib\site-packages\pgmpy\estimators\__init__.py)
```

Apparently, pgm replaced `ConstraintBasedEstimator` with subpackage `PC` . See https://github.com/pgmpy/pgmpy/tree/dev/pgmpy/estimators 

It looks like the fix is commented out in `bnlearn/structure_learning.py`:

```
  from pgmpy.estimators import ConstraintBasedEstimator
  # from pgmpy.estimators import PC as ConstraintBasedEstimator
```

Let me know if it may be a problem with the installation process used:

```
> pip install bnlearn
> pip install pgmpy
```

The installed versions are bnlearn==0.3.11,   pgmpy==0.1.12.
This is running on current windows 10.

**Comment by jmagosta** [comment]
A work-around is to install the previous pgmpy version from the whl file: pgmpy-0.1.11-py3-none-any.whl

**Comment by erdogant** [comment]
Thats correct, I incorporated the PC from the latest pgmpy version but this resulted in issues in the computations. I returned to the ConstraintBasedEstimator from an earlier version of pgmpy. I would recommend to install pgmpy=='0.1.11' as described in the requirements.txt file. But also the following:

pgmpy=='0.1.11'
networkx>='2.5'
matplotlib>='3.3.2'
