### ISSUE TITLE
Implemented Structure Learning Algos

### ISSUE THREAD

**Issue by arainboldt** [erdogant/bnlearn#16]
Hello,

Great package! I'm just getting into exploring the API and was curious if the Chow Liu algorithm is implemented in the structure learning module under a different name. If not, any plans to implement it? 

Thanks!

Andrew

**Comment by erdogant** [comment]
Thanks! The Chow Liu algorithm is great! It was not included yet. But I directly implemented into bnlearn!
happy coding!

Update latest version with:
```
pip install -U bnlearn
import bnlearn
bnlearn.__version__ # should be 0.3.12

```

**Comment by arainboldt** [comment]
Thanks a lot for your quick response and implementing this! Awesome!
