### ISSUE TITLE
Predict on a new dataset

### ISSUE THREAD

**Issue by ponnet** [erdogant/bnlearn#17]
More of a question - the examples given only deal with the explicit values in bnlearn.inference.fit
How can I feed in a new dataset and get prediction on all the records? 

One more clarification: How can I get prediction on the values that haven't been in the data (a particular factor level)? I know in R one can explicitly specify many more levels...

**Comment by erdogant** [comment]
Some examples can be found on the documentation pages that includes how to
import bif file, how to work with raw datasets and more:
https://erdogant.github.io/bnlearn/pages/html/Examples.html
If you want to make inferences, that is possible with bnlearn but if you
want to make predictions on your data, you may want to use classification
methods (?) Naive bayes is one way to do that
https://scikit-learn.org/stable/modules/naive_bayes.html


Op di 2 feb. 2021 om 00:52 schreef ponnet <notifications@github.com>:

**Comment by ponnet** [comment]
Thank you, Erdogan.

I did look through examples and saw that what I really need is to use the model I built to get  the probability of belonging to a particular class:
`bnlearn.inference.fit(DAG, variables=['Wet_Grass'], evidence={'Rain':1, 'Sprinkler':0, 'Cloudy':1})`

As I usually use R, there is a simple `predict` statement there that gives those probabilities for the data frame you supply. 

I can dig the Naive Bayes prediction and if it can take `bnlearn ` model, but I hoped there is an easier way to supply the whole new dataset and get those probabilities from `bnlearn `directly.

**Comment by erdogant** [comment]
I see, the inference function does output the probabilities that you can use. Although I may need to restructure it a bit.

Example:

```
import bnlearn as bn
model = bn.import_DAG('sprinkler')
q_1 = bn.inference.fit(model, variables=['Rain'], evidence={'Cloudy':1})

# print(dir(q_1))
print(q_1)
print(q_1.values)
print(q_1.variables)

# +---------+-------------+
# | Rain    |   phi(Rain) |
# +=========+=============+
|#  Rain(0) |      0.2000 |
# +---------+-------------+
|#  Rain(1) |      0.8000 |
# +---------+-------------+
# [0.2 0.8]
# ['Rain']

```

**Comment by ponnet** [comment]
Yes, exactly! 
I managed to use 1 line at a time from the new dataset converting it to `json`.

However, using the whole data frame at once is still not working...

**Comment by erdogant** [comment]
Can you make a small example to demonstrate it?

**Comment by wangwei18** [comment]
Hi, Erdogan. basically like this, predictions = bn.predict(df, "column name"). it can predict any column in the data frame with discreate value that has the highest probability.. There is another python package called CausalNex that can do prediction for entire data frame. Your package BNLearn has much better structure learning and inference accuracy. But inference fit function requires implicitly spelling out all non-target column names and only fit one row of data and only provide probabilities..

**Comment by erdogant** [comment]
I implemented the predict functionality that can now be used from version >= 0.3.20

update the library with:
`pip install -U bnlearn
import bnlearn
bnlearn.__version__`

Examples and documentation can be found in the readme and sphinx pages:
https://erdogant.github.io/bnlearn/pages/html/Predict.html
