### ISSUE TITLE
Simulating data

### ISSUE THREAD

**Issue by timhuang1125** [erdogant/bnlearn#18]
Hi Erdogant, I have some questions.
Because my data is not balanced, I need to simulate the data through the Bayesian network.
Below is my code and Error messsage:

#------code------#
import bnlearn
import pandas as pd
import matplotlib.pyplot as plt

train_df = pd.read_excel('C:\\Users\\timhuang\\Documents\\分析報告\\資料不平衡處理方法及效益評估\\xlsx\\11to18_train_tttt.xlsx')
train_df_filter = train_df[train_df['result'] == 'No']
n_train_df = train_df_filter.drop(['簽審核准許可文件編號', '受理日期', '報單項次', 'result'], axis=1)
train2one, train2num = bnlearn.df2onehot(n_train_df)
DAG = bnlearn.structure_learning.fit(n_train_df)
plt.rcParams['font.sans-serif'] = ['Taipei Sans TC Beta']
G = bnlearn.plot(DAG)
model = bnlearn.parameter_learning.fit(DAG, train2num)
bnlearn.print_CPD(model)
df = bnlearn.sampling(DAG, n=1000)
#------code------#
ValueError: Model must contain DAG from BayesianModel. Note that <misarables> example does not include DAG.

H~E~L~P ><

**Comment by erdogant** [comment]
`model = bnlearn.parameter_learning.fit(DAG, train2num)`

should be:

`DAG = bnlearn.parameter_learning.fit(DAG, train2num)`

The CPDs that are from train2num are learned for the DAG and stored in the DAG. The output dict contains the model, the DAG and the CPDs that are used in the sampling.

**Comment by timhuang1125** [comment]
Hi Erdogant, I have another question ><

Why is my data variable originally 64, but 50 after the simulation?

**Comment by timhuang1125** [comment]
Hi Erdogant, I have another question ><
My data had 64 variables, but only 50 after the simulation. QAQ Why?

**Comment by erdogant** [comment]
I did look into this issue but could not directly replicate it. However, I did find a small issue that I fixed. When using black_list or white_list, you must now provide the bw_list_method. However, bw_list_method was readily set when using 'hc' method. This is fixed now. Update to the latest version and give it a try :

```
pip install -U bnlearn
import bnlearn as bn
print(bn.__version__)

```

**Comment by timhuang1125** [comment]
Hi Erdogant, I have some questions.

1. My class variable(result) contains YES and NO. I only need to generate NO data. What should I do?
2. The last node of the DAG is the class variable. How do I specify the class variable(result)?
`DAG = bnlearn.structure_learning.fit(n_train_df)` ->`DAG = bnlearn.structure_learning.fit(n_train_df, class='result')`
