### ISSUE TITLE
Integrate new models

### ISSUE THREAD

**Issue by arita37** [erdogant/bnlearn#2]
This is great work.
What about the design 
to integrate new models ?

**Comment by erdogant** [comment]
Good point. I will see how I can refactor the code so that other code can be more easily implemented. Do you have any suggestions for design?

**Comment by arita37** [comment]
Similar to sklearn :


fit()
predict()
transform()
get_metrics()

**Comment by arita37** [comment]
Am working on generic API:
It can be re-used in some ways.

https://github.com/arita37/mlmodels/tree/dev

Wr can discuss here.
