### ISSUE TITLE
Hi Erdogant, I have some questions.

### ISSUE THREAD

**Issue by erdogant** [erdogant/bnlearn#21]
Hi Erdogant, I have some questions.

1. My class variable(result) contains YES and NO. I only need to generate NO data. What should I do?
2. The last node of the DAG is the class variable. How do I specify the class variable(result)?
`DAG = bnlearn.structure_learning.fit(n_train_df)` ->`DAG = bnlearn.structure_learning.fit(n_train_df, class='result')`

_Originally posted by @timhuang1125 in https://github.com/erdogant/bnlearn/issues/18#issuecomment-787995563_

**Comment by timhuang1125** [comment]
?
