### ISSUE TITLE
Error in Docu?

### ISSUE THREAD

**Issue by adrianlubitz** [erdogant/bnlearn#25]
Hi,
I just scanned the docu to see if this is applicable to my usecase and I stumbled upon this:

```python
cpt_cloudy = TabularCPD(variable='Cloudy', variable_card=2, values=[[0.5], [0.5]])
print(cpt_cloudy)
```

|      |      | 
| ------------- |:-------------:| 
| Cloudy(0) | 0.3 |
| Cloudy(1) | 0.7     | 

As far as I understood the `values` in the  `TabularCPD` it should be 
|      |      | 
| ------------- |:-------------:| 
| Cloudy(0) | 0.5 |
| Cloudy(1) | 0.5     | 

*50/50 is also the defined probability for this example in the literature*

This is defined in https://github.com/erdogant/bnlearn/blame/master/docs/pages/html/_sources/Create%20DAG.rst.txt#L98

Correct me if I'm wrong otherwise you're welcome ;)

**Comment by erdogant** [comment]
You are correct!
I changed the values to 0.3 and 0.7 and updated the pages
