### ISSUE TITLE
Parameter Learning MLE estimation is broken

### ISSUE THREAD

**Issue by ssomanch** [erdogant/bnlearn#27]
The maximum likelihood estimation in parameter learning, fit(model, df, methodtype='ml', verbose=3), estimates the CPDs using MLE but then the model returned is MaximumLiklihoodEstimator not a BayesianModel class. The code needs to be modified as below in parameter_learning.py

```
if config['method']=='ml' or config['method']=='maximumlikelihood':
   model.fit(df, estimator=None) # estimator as None makes it maximum likelihood estimator according pgmpy docs. 
    for cpd in model.get_cpds():
        if config['verbose']>=3: print("CPD of {variable}:".format(variable=cpd.variable))
        if config['verbose']>=3: print(cpd)
```

**Comment by erdogant** [comment]
Great! I updated and created a new release.
update with:

`
pip install -U bnlearn
`

**Comment by ssomanch** [comment]
Great, thank you!
