### ISSUE TITLE
Augmented Naive Bayes

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#32]
Hi!

My name is Pablo Rodríguez and first at all thank you for so useful library! Do you have thought in include Augmented Naive Bayes algoritmhs? Unless, do you need some library written in python code?

All best,
Pablo

**Comment by erdogant** [comment]
Thanks! Sounds like a nice additional approach! Is it a installable library or a function? If you like, you can make a pull request, or alternatively you can send the code. I will incorporate it then.

**Comment by PARODBE** [comment]
You can incorporate the algorithm in this library: https://pgmpy.org/examples/Structure%20Learning%20with%20TAN.html   May be it is interesting for you to do a adaptation of this library. What do you think? Although, I think that you have the chow liu algorithm in your library which is a tree augmented naive bayes???

**Comment by erdogant** [comment]
The chow liu algorithm is a treesearch approach, just like Tree-augmented Naive Bayes (TAN).
I integrated this method into bnlearn! You can update with:

`pip install -U bnlearn

import bnlearn as bn
df = bn.import_example()
# Structure learning with TAN
model = bn.structure_learning.fit(df, methodtype='tan', root_node='Cloudy', class_node='Rain')
bn.plot(model)

`

**Comment by PARODBE** [comment]
Oooh great!  Thank you @erdogant ! I have another question, when you use the predict function, you obtain a dataframe with prediction and probabilities according to your variables which you add in the function predict in your example are rain and cloudy. The probability is the probability of Wet_grass, and the predictions is the prediction of wet_grass for cloudy using cloudy as a variable for example?

The last questions are that the library of R which was using the last week incorporates a cross validation function obtaining the accuracy with a KFold. I was doing manually with KFold().split but it was very slow and the same for likehood option. Also, I have been looking for oede naive bayes and I found it in bnclassify (in R) library for it was interesting for you.

Thanks for all! I love your library!

Pablo

**Comment by erdogant** [comment]
> Oooh great! Thank you @erdogant ! I have another question, when you use the predict function, you obtain a dataframe with prediction and probabilities according to your variables which you add in the function predict in your example are rain and cloudy. The probability is the probability of Wet_grass, and the predictions is the prediction of wet_grass for cloudy using cloudy as a variable for example?
> 
> The last questions are that the library of R which was using the last week incorporates a cross validation function obtaining the accuracy with a KFold. I was doing manually with KFold().split but it was very slow and the same for likehood option. Also, I have been looking for oede naive bayes and I found it in bnclassify (in R) library for it was interesting for you.
> 
> Thanks for all! I love your library!
> 
> Pablo

I created a new issue #33 regarding this question.
