### ISSUE TITLE
Structure Learning chow-liu method not working

### ISSUE THREAD

**Issue by SachSpace** [erdogant/bnlearn#34]
Hi, I tried to run the chow-liu structure learning method on a simple dataset with 3 variables. But, I'm getting an error as attached. It seems like chow-liu algorithm is not in bnlearn.  I have installed **bnlearn 0.3.11 in anaconda**. Seems like there is no new update available yet. I was wondering how to fix this.  I even checked the `fit` function in `structure_learning.py`, I only see 3 methods as ;

>         1. Score-based structure learning (BIC/BDeu/K2 score; exhaustive search, hill climb/tabu search)
>             a. exhaustivesearch
>             b. hillclimbsearch
>         2. Constraint-based structure learning (PC)
>             a. chi-square test
>         3. Hybrid structure learning (The combination of both techniques) (MMHC)
>        

Is there any way to run the chow-liu algorithm ? or else anyway to fix this issue? Thank you ! 

![image](https://user-images.githubusercontent.com/65580987/131575530-ab693526-ff95-4328-8c26-5bde8705e066.png)

**Comment by erdogant** [comment]
Can you try to update to the latest version first?
`
pip install -U bnlearn`

It should be version >= 0.4.0

**Comment by SachSpace** [comment]
Oh now that it is working! Thank you so much! Initially, the anaconda navigator did not show any update option for bnlearn. But, after trying `pip install -U bnlearn` in the Spyder console, it works. Now that I have bnlearn version 0.4.0.

**Comment by erdogant** [comment]
Nice! have fun!
