### ISSUE TITLE
How to change node colors ? 

### ISSUE THREAD

**Issue by SachiniEMSPE** [erdogant/bnlearn#35]
Hi, 
I'm using this package for structure learning. This is great! Meanwhile, I tried to plot the learned Bayesian network structure using `bn.plot(G)` but, with different node colors. I looked at the `plot` function in bnlearn.  I only see  _model, pos, scale, figsize, verbose_ as parameters but not colors. I was wondering whether is there any method to use to change node colors? 
Thank you!

**Comment by erdogant** [comment]
Great to hear! 
How is your suggestion to do this?

**Comment by SachiniEMSPE** [comment]
Well... I think two lines (1. `plot()` 2. `nx.draw_networkx_nodes()`) are required to update. 🤔
How about updating `plot` function to something like `def plot(model, pos=None, scale=1, figsize=(15, 8), verbose=3, **node_color**)`. I mean add another parameter (input should be in hexa color format e.g. : #1fb4a6) to `plot` which will be then used in `nx.draw_networkx_nodes` function inside `plot`.  E.g., existing version is  `nx.draw_networkx_nodes(G, pos, node_size=500, alpha=0.85)` . Added parameter is required to used inside like `nx.draw_networkx_nodes(G, pos, node_size=500, alpha=0.85, **node_color="node_color"**)`. So that existing `node_color="#1f78b4"` will be changed to "#1fb4a6". 
What do you think ? 😃

**Comment by erdogant** [comment]
ok I see! But don’t you want to have the possibility to color each node separately?

What about:

node_color = dict{“nodeA”: “#1f78b4”, “nodeB”:”#xxx”, …}

**Comment by SachiniEMSPE** [comment]
Oh, initially I wanted to change node colors for different networks instead of the default color. So that, I can differentiate two graphs. However, having the option to change each node color per graph is also great. Well... for that, I think your suggestion would work.

**Comment by SachiniEMSPE** [comment]
Ooh examples in the docs look great! Thank you so much @erdogant ! I will try the new version. 😀
