### ISSUE TITLE
Continous data

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#36]
Hi again!

I was thinking in using bayesian networks for continous data, do you think that an implementation in order to work with these kind of data could be possible?

Thanks!

**Comment by erdogant** [comment]
At the moment bnlearn can only be used for discrete/categorical analysis. Implementing models that can work with continuous values is on my (long) todo list.

Nevertheless, there are possibilities to model your data if you have continuous data. You may can discretize your variables with domain/experts knowledge. For example, if you have temperature, you can mark temperature < 0 as freezing, and
>0 as normal. Or many more smaller categories.

**Comment by rafmora** [comment]
Any update as of today regarding to implementing the continuous values?

**Comment by erdogant** [comment]
Not yet but I'm planning to give it a start soonish. If you have any suggestions, working examples or methods to start with, let me know.

**Comment by rafmora** [comment]
Yes. Happy to help with examples. I am currently modeling soil corrosivity in Python.
Please let me when you would like to start so I can prepare a easy-to-start example.

**Comment by thomasfrederikhoeck** [comment]
Cheers for your work @erdogant . Do you have any kind of ETA on this ? :-)

**Comment by erdogant** [comment]
Yes Soonish! Hopefully shortly after the summer break if august! #wishfullthinking

**Comment by samanemami** [comment]
> Yes Soonish! Hopefully shortly after the summer break in august! #wishfullthinking

Please count on me for adding the feature to the model.
Thanks

**Comment by samanemami** [comment]
@erdogant Have you seen this [continuous ](https://github.com/sisl/LearnDiscreteBayesNets.jl/blob/master/src/L_DVBN.jl)approach?

**Comment by erdogant** [comment]
Thank you for spotting this repo! But the repo seems to support also only discrete models.

**Comment by samanemami** [comment]
I am thinking of applying their continuous approach to bnlean!

**Comment by erdogant** [comment]
If you can get it up and running with an example for continuous data, It would be great! But the name of the repo I am seeing is [LearnDiscreteBayesNets.jl], which hints towards discrete models.

**Comment by samanemami** [comment]
@erdogant [This ](https://www.jair.org/index.php/jair/article/view/11063)is its related [paper](https://www.jair.org/index.php/jair/article/view/11063).
And [here](https://github.com/sisl/LearnDiscreteBayesNets.jl/blob/master/src/L_DVBN.jl#L965), the used function, I guess!

**Comment by fimselamse** [comment]
@samanemami I think the function you are referring to simply discretizes the data before learning the network.

**Comment by samanemami** [comment]
@fimselamse Yes, that is the idea. Couldn't we use it?

**Comment by erdogant** [comment]
Very interesting though! I am going to read the paper first :-)

**Comment by fimselamse** [comment]
@samanemami Yes, this is definitely way to create a network from continous data. However, it is not what's being done in the R bnlearn library. They use a special gaussian case of the scoring function, if I understand it correctly.

**Comment by samanemami** [comment]
Perfect @erdogant, count on me.

@fimselamse, Yes. This is not the method used in R, but this package could add other methods to handle the continuous data as well.

**Comment by fimselamse** [comment]
@samanemami Definitely! I have tried some information preserving discretization methods myself. Some results were promising, but not as good as the method used in R. Would love to see the results with this one, though!

**Comment by erdogant** [comment]
I have been looking into this peace of code it is written in Julia (I was hoping Python #wishfullthinking). Maybe not a huge issue but manually converting it is kind of error-prone and time-consuming. I did find a [converter](https://cjdoris.github.io/PythonCall.jl/dev/conversion-to-python/) to Python. I will give that a try first.

**Comment by rafmora** [comment]
@erdogant regarding real case examples of continuous data (e.g., corrosion), please let me know if I can be of help. Interested to test them using bnlearn. When would you expect to start the new version testing?

**Comment by erdogant** [comment]
I added the julia code in the github. I did an attempt to manually rewrite it to Python but without being experienced in Julia, it was quite intensive. Now I am thinking to create a small use case to use ChatGPT to let it rewrite it to Python. However, In my experience, the code that chatGPT generates can be buggy and not always correct. Nevertheless, it may be a good starting point to bugfix and rewrite!

**Comment by erdogant** [comment]
It took a while but in the latest release, there is now an implementation for continuous data modeling! 
There are many unit tests to ensure the quality and validity of the results but I did not use it in a real-life scenario yet.

Check it out in the [docs](https://erdogant.github.io/bnlearn/pages/html/Continuous%20Data.html).

**Comment by erdogant** [comment]
I am closing this one as there is now a basis functionality that can process continous data!
See the [documentations](https://erdogant.github.io/bnlearn/pages/html/Continuous%20Data.html#) for more details.
