### ISSUE TITLE
Differents results

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#38]
Hi,

I have one question. Why am I obtaining different results usin tan algorithm of this library and using treesearch of pgmpy? are different the implementations?

Thanks!

**Comment by erdogant** [comment]
Should the same. Maybe different default settings. Can you post an example?

**Comment by PARODBE** [comment]
est = TreeSearch(df)
dag = est.estimate(estimator_type="tan",class_node='Target')
bn = BayesianModel(dag.edges())
bn.fit(df)


And now in bnlearn:

model = bnlearn.structure_learning.fit(df, methodtype='tan',class_node='Target', scoretype='bic')
model_bn = bnlearn.parameter_learning.fit(model, df)

**Comment by erdogant** [comment]
If you do the structure learning, the results are similar in my example.

```
from pgmpy.estimators import TreeSearch
import bnlearn as bn

# Import example
df = bn.import_example(data='asia')

# Do the tan learning
est = TreeSearch(df, root_node='smoke')
dag = est.estimate(estimator_type="tan",class_node='lung')

# And now with bnlearn
model = bn.structure_learning.fit(df, methodtype='tan', root_node='smoke', class_node='lung')

# Compare results
assert dag.edges()==model['model'].edges()

```

**Comment by PARODBE** [comment]
Do you think that in my case could be because I haven't specify the root_node with bnlearn?

**Comment by PARODBE** [comment]
In pgmpy as you know it is necessary implement a function in order to prune the nodes, maybe this is another reason which the results of my dataframe are differents, what do you think?

**Comment by erdogant** [comment]
If I don't add a root node, it throws an error:

```
est = TreeSearch(df)
TypeError: __init__() missing 1 required positional argument: 'root_node'

```

Which version are you using of pgmpy and bnlearn?
```
import pgmpy
print(pgmpy.__version__)
'0.1.13'

import bnlearn
bnlearn.__version__
'0.4.1'
```

**Comment by PARODBE** [comment]
Pgmpy : 0.15.0

Bnlean i can remember but the last, because I uploaded in order to obtain the plots so cools that you implemented:)

**Comment by erdogant** [comment]
I see! I updated pgmpy and now it does not throw an error anymore.

Thre results are still the same though:

```
from pgmpy.estimators import TreeSearch
import bnlearn as bn

# Import example
df = bn.import_example(data='asia')

# Do the tan learning
est = TreeSearch(df)
dag = est.estimate(estimator_type="tan",class_node='lung')

# And now with bnlearn
model = bn.structure_learning.fit(df, methodtype='tan', class_node='lung')

# Compare results
assert dag.edges()==model['model'].edges()
assert dag.edges()==model['model_edges']

```

Can you demonstrate it with a dataset where this is not the case?

**Comment by erdogant** [comment]
> In pgmpy as you know it is necessary implement a function in order to prune the nodes, maybe this is another reason which the results of my dataframe are differents, what do you think?

Do you mean `edge_weights_fn`? It seems to be optional: https://pgmpy.org/structure_estimator/tree.html

**Comment by PARODBE** [comment]
If I run your code with assert, nothing happens, therefore they are supposed to be the same. However, if I do inference with pgmpy for one variable of my dataset, the result is:

![image](https://user-images.githubusercontent.com/62376157/133852831-5e1ea57a-47cb-427c-9989-dd8673ca64b7.png)

However for the same variable, the result is:

![image](https://user-images.githubusercontent.com/62376157/133852926-7c4b51fd-080c-423d-a0c7-f7a2db3bbfca.png)

After of build the model with bnlearn I do:

model_bn = bnlearn.parameter_learning.fit(model, df)

and after I do the inference....

**Comment by PARODBE** [comment]
And in order to do inference with pgmpy you have to do:

from pgmpy.inference import VariableElimination
bn_infer = VariableElimination(bn)

a = bn_infer.query(variables=['Target'], evidence={'X':'c'})
print(a)

Unless you can't do inference no? and if you apply variable elimination you are prune nodes....

**Comment by erdogant** [comment]
If you can reproduce the differences with the same parameters for one of the example datasets (as below), I can look into it. There are many steps between raw dataframe towards making inferences. First creating the DAG, then parameter learning, and finally making inferences. If you want to know where exactly the differences occur, do **not** use the default settings. 

Thus for structure learning, you used the method type **tan** but also define the scoring function (bic, k2, bdeu). For parameter learning set the method type (ml or bayes).  The inference is just a realization of however the model is defined. Can you give that a try?


`df = bn.import_example(data='asia')
`

**Comment by PARODBE** [comment]
Ok. For example.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pgmpy.estimators import TreeSearch
from pgmpy.models import BayesianModel
import networkx as nx
import bnlearn as bnlearn
from pgmpy.inference import VariableElimination
from pgmpy.estimators import BDeuScore, K2Score, BicScore

df=bnlearn.import_example(data='andes')

est = TreeSearch(df)
dag = est.estimate(estimator_type="tan",class_node='DISPLACEM0')
bn = BayesianModel(dag.edges())
bn.fit(df)

bn_infer = VariableElimination(bn)
a = bn_infer.query(variables=['DISPLACEM0'], evidence={'RApp1':1})
print(a)

![image](https://user-images.githubusercontent.com/62376157/133885869-956d387f-dece-4d19-90db-d304d9ef8837.png)

Now with bnlearn:

model = bnlearn.structure_learning.fit(df, methodtype='tan', class_node='DISPLACEM0',scoretype='bic')
model_bn = bnlearn.parameter_learning.fit(model, df)

query=bnlearn.inference.fit(model_bn, variables=['DISPLACEM0'], evidence={'RApp1':1})

![image](https://user-images.githubusercontent.com/62376157/133885896-440ca60c-3af5-40ed-9b39-4d4e2f7b2435.png)


I know that the results are very close, but they aren't exactly equal. And in my dataframe for example I get a difference in some inferences about 0.15.... 

What do you think?

Thanks for all!

**Comment by PARODBE** [comment]
I am looking and there are a great quantity of functions in order to do an inference in pgmpy. I am testing some kind of these, but in your opinion do you think that It could be reason for obtaining different results?

![image](https://user-images.githubusercontent.com/62376157/133887629-6b02ab7a-231a-41e3-91bc-f281481f41d2.png)

**Comment by erdogant** [comment]
A great part of the core of bnlearn is build on pgmpy. Therefore I do not expect different results besides using different parameters as an input.

**Comment by PARODBE** [comment]
Upps then, I don't know why the results have some differences ...

**Comment by PARODBE** [comment]
Hi,

I have been using bnlearn in R and doing inference in the same query in my dataframe, the result are close to pgmpy, look at:

library(bnclassify)
library(bnlearn)
df[c(colnames(df))] <-lapply(df[c(colnames(df))], factor)
tan = tree.bayes(df, "Target")
fitted = bn.fit(tan, df, method = "bayes")

cpquery(fitted, event = (Target==1), evidence = ( A=="b"))

In pgmpy, the result was 0.82, in bnlearn 0.70 y en bnlearn of R 0.84. I don't understand it, and morever i love your library!

**Comment by erdogant** [comment]
Ah now I see the difference. It is in the parameter learning part. In the pgmpy example, you are using maximum likelihood and in bnlearn you specify bic as estimator. If you change this line you get exactly the same results:

`model = bnlearn.structure_learning.fit(df, methodtype='tan', class_node='DISPLACEM0',scoretype='ml')
`

**Comment by PARODBE** [comment]
OOh thank you very much, but I can't implement scoretype='ml'. I get the next error : scoretype must be string: "bic", "k2" or "bdeu".

I have uploaded for if It was necessary but I continue obtaining the same error. Could you help me please? Thanks!

**Comment by erdogant** [comment]
See here for the full comparison of DAG, CPD variable names and CPD probabilities:

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pgmpy.estimators import TreeSearch
from pgmpy.models import BayesianModel
import networkx as nx
import bnlearn as bnlearn
from pgmpy.inference import VariableElimination
from pgmpy.estimators import BDeuScore, K2Score, BicScore
import bnlearn as bn


df=bnlearn.import_example(data='andes')

# PGMPY
est = TreeSearch(df)
dag = est.estimate(estimator_type="tan",class_node='DISPLACEM0')
bnq = BayesianModel(dag.edges())
bnq.fit(df, estimator=None) # None means maximum likelihood estimator
bn_infer = VariableElimination(bnq)
q = bn_infer.query(variables=['DISPLACEM0'], evidence={'RApp1':1})
print(q)

# BNLEARN
model = bnlearn.structure_learning.fit(df, methodtype='tan', class_node='DISPLACEM0', scoretype='bic')
model_bn = bnlearn.parameter_learning.fit(model, df, methodtype='ml') # maximum likelihood estimator
query=bnlearn.inference.fit(model_bn, variables=['DISPLACEM0'], evidence={'RApp1':1})

# DAG COMPARISON
assert np.all(model_bn['adjmat']==model['adjmat'])
assert dag.edges()==model['model'].edges()
assert dag.edges()==model['model_edges']

# COMPARE THE CPDs names
qbn_cpd = []
bn_cpd = []
for cpd in bnq.get_cpds(): qbn_cpd.append(cpd.variable)
for cpd in model_bn['model'].get_cpds(): bn_cpd.append(cpd.variable)

assert len(bn_cpd)==len(qbn_cpd)
assert np.all(np.isin(bn_cpd, qbn_cpd))

# COMPARE THE CPD VALUES
nr_diff = 0
for cpd_bnlearn in model_bn['model'].get_cpds():
    for cpd_pgmpy in bnq.get_cpds():
        if cpd_bnlearn.variable==cpd_pgmpy.variable:
            if not np.all(cpd_bnlearn.values==cpd_pgmpy.values):
                print('%s-%s'%(cpd_bnlearn.variable, cpd_pgmpy.variable))
                print(cpd_bnlearn)
                print(cpd_pgmpy)
                nr_diff=nr_diff+1
                input('press enter to see the next difference in CPD.')

```

**Comment by erdogant** [comment]
> OOh thank you very much, but I can't implement scoretype='ml'. I get the next error : scoretype must be string: "bic", "k2" or "bdeu".
> 
> I have uploaded for if It was necessary but I continue obtaining the same error. Could you help me please? Thanks!

I updated my previous message. I accidently copy-paste the wrong line. It should work now.

**Comment by PARODBE** [comment]
Now yes!!! thank you very much!!! and I feel so much message! You've been very kind! :)

**Comment by erdogant** [comment]
No worries. I’m glad we resolved this issue!
