### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ssimontacchi** [erdogant/bnlearn#4]
Thanks so much for working on this! I am learning causality now and don't want to learn R, so I definitely appreciate your work. 

I was looking at [this example on the bnlearn site](https://rpubs.com/osazuwa/causaldag1) and trying to recreate it. Is it possible yet or could you use some more pull requests first?

Thanks so much!

**Comment by erdogant** [comment]
Thank you! The examples shown at the website seems possible with the current functionality.
In the function "_DAG_sprinkler" in the bnlearn.py file is an example how to create a DAG and combine it with CPDs. Im also working on creating a doc pages using sphinx. I can then also include such a nicely illustrated example.

**Comment by erdogant** [comment]
I created documentation! I hope this allows you to re-make your R example in bnlearn just by following some of the examples.

https://bnlearn.readthedocs.io/
