### ISSUE TITLE
How to fix the order of variables in an inference result ?

### ISSUE THREAD

**Issue by SachiniEMSPE** [erdogant/bnlearn#40]
Hi @erdogant , 👋

I tried to make the same inference using a list of DAGs (with a total of 5 variables) as below. 
`prob = bn.inference.fit(G_list[k],variables=['X3','X1','X2'], evidence={},verbose=3)`
`prob_df = prob.values`.
I'm interested in finding variable values for a certain phi () value using the ` prob_df `index. However, I noticed that every time I'm getting a different order of variables as attached below. 
I was wondering whether there is any way to fix that output variable order? I even tried sending a fixed variable elimination order. But, it didn't work. I would appreciate any suggestions on this? 🤔 
Thank you! 🙏

```
+-------+-------+-------+-----------------+
| X2    | X3    | X1    |   phi(X2,X3,X1) |
+=======+=======+=======+=================+
| X2(0) | X3(0) | X1(0) |          0.0224 |
+-------+-------+-------+-----------------+
| X2(0) | X3(0) | X1(1) |          0.6438 |
+-------+-------+-------+-----------------+

+-------+-------+-------+-----------------+
| X2    | X1    | X3    |   phi(X2,X1,X3) |
+=======+=======+=======+=================+
| X2(0) | X1(0) | X3(0) |          0.0554 |
+-------+-------+-------+-----------------+
| X2(0) | X1(0) | X3(1) |          0.0595 |
+-------+-------+-------+-----------------+`
```

**Comment by erdogant** [comment]
Good point. I changed it and released a new version!

Update with:
`pip install -U bnlearn`

Try this instead:

```
prob = bn.inference.fit(G_list[k],variables=['X3','X1','X2'], evidence={},verbose=3)
prob.df

```

**Comment by SachiniEMSPE** [comment]
Thank you for updating! However, after updating bnlearn to 0.4.6, I'm getting an error `(ModuleNotFoundError: No module named 'tabulate')` as attached. Seems like I cannot run bnlearn. Do you have any suggestions on that? Thanks! 
![image](https://user-images.githubusercontent.com/48669988/143141704-41332ad1-09a8-4a65-8a25-ce098a36a0b7.png)

**Comment by erdogant** [comment]
I added the tabulate package to the setup file now. Try to pip install again.

`pip install -U bnlearn
`

**Comment by SachiniEMSPE** [comment]
I see. Now it works! 😃 Thank you!

**Comment by erdogant** [comment]
have fun! :)
