### ISSUE TITLE
Statistical differences between inferences

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#41]
Hi!

One question, when you have inferences in a variable with more of two categories. How could you say that the differences are consistent? It is more a statistical question..haha.

Thanks!

**Comment by erdogant** [comment]
Maybe you can shuffle your dataset and do the exact same computation again. Obviously you would expect random results. Repeat this like 1000x and count how often you see certain results. Maybe then you can use this 1D vector (depicts results with nonsense/random results) to demonstrate that your real results differ from results using a randomized dataset?

**Comment by PARODBE** [comment]
It is a good option, although could be that the inferences with three or 4 variables are under represented...

**Comment by erdogant** [comment]
I am closing this issue. If you already have a solution for this, post it here or otherwise re-open when this still is an issue.
