### ISSUE TITLE
Naive Bayes

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#42]
Hi @erdogant ,

One question, for create a Naive Bayes using bayesian networks is not possible in this library?

Thanks!

**Comment by erdogant** [comment]
Do you mean a classification model?

**Comment by PARODBE** [comment]
Nop, in this case I would use, scikit-learn, I want to say a probabilistic model but naive bayes, like in pgmpy for example: https://pgmpy.org/models/naive.html  or in bnlear of r (https://www.bnlearn.com/). But I love your library and it was wonderful have this option here, because is the most basic assumption to start with a naive bayes also in probabilistic model...I don't know, what do you think?

**Comment by erdogant** [comment]
ah nice! I see. Seems like easy going. I will look into this!

**Comment by PARODBE** [comment]
oooh! thank you very much!!! It's curious, I'm obtaining the same results with a tan,score type=bic and method type= Maximum likelihood in bnlearn and with simple Naive bayes of pgmpy, may be It is a coincidence. Could you say me anything when you incorporate Naive Bayes, please? Then, I'll update to the new version. Thanks for all! :)

**Comment by erdogant** [comment]
If you update to the latest version, you can try it out!

`pip install -U bnlearn`

I also added the naivebayes approach to the documentation:
https://erdogant.github.io/bnlearn/pages/html/Structure%20learning.html#naivebayes

**Comment by PARODBE** [comment]
Uoo thanks @erdogant . Do you know? The other day I was thinking about extracting feature importances using bayesian networks, I was using different aproximations like permutation for example, but It would be very interesting to have another approximations. You know that the model interpretability each time is more relevant, and there are different libraries that you know I am sure. And there are one possibility for example with Shap using kernelexplainer, where you can obtain feature importance for whatever model. And I don't know libraries with bayesian networks which incorporate this option, I don't know if the reason is by complication or another kind of aspects.

Another aspect that I would like tell you is that in R there are two hyperparameters for build a bayesian networks which are very important for the variability of the inferences, the name is 'Smooth', this argument you can get it in bnclassify library in r, and for example in bnlearn in r the argument I am not sure if is the same but It could be the argument 'iss'??.  

Also, in my opinion could be interesting to incorporate in this library a predict proba function like in pgmpy for example: https://pgmpy.org/_modules/pgmpy/models/BayesianModel.html

Sorry for the brainstorming, but I like your library and I think that these things could make this library unique...

Thanks!

**Comment by erdogant** [comment]
Thanks for the suggestion! 
I will close this issue because the last question is becoming something new again I guess.
