### ISSUE TITLE
Change the edge style of DAG in bnlearn

### ISSUE THREAD

**Issue by WhySeeYC** [erdogant/bnlearn#43]
Hi,
May I ask if it is possible to style the edge of the DAG in bnlearn library?
I know that we can change node size, color, etc., but the documentation did not provide much information on whether we can change the style of the edges (e.g. make the arrow head bigger, thicker). 
Thank you.

**Comment by erdogant** [comment]
Hi! This feature was not possible but it is now from version 0.4.9 !

* edge properties can be changed for plotting purposes
   * color (per edge)
   * weight (per edge)
   * edge_alpha (overall)
   * arrowstyle (overall)
   * arrowsize (overall)

update bnlearn with:

`pip install -U bnlearn
`
I included an example in the readme file!

**Comment by erdogant** [comment]
With the documentation over here: https://erdogant.github.io/bnlearn/pages/html/Plot.html#edge-properties

**Comment by WhySeeYC** [comment]
This is amazing! Thank you so much!
