### ISSUE TITLE
arc.strength bnlearn r implementation

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#44]
Hi again @erdogant ,

Do you think that could be easy implement the strength of the relations of the nodes like in r??? It could be interesting...https://www.rdocumentation.org/packages/bnlearn/versions/0.8/topics/arc.strength

thanks!

**Comment by erdogant** [comment]
Great suggestion. I will look into this.

**Comment by PARODBE** [comment]
Thanks @erdogant , moreover the strength can be represented in the neural network graph for example in bnlearn library of r you can do it using a Bic score or chi square (there are more possibilities I am sure), and after you could put for example bold arrow for statistical significant relations between nodes, and also you can choose the different threshold of p value (0.5,0.01,0.001 etc...), there are a great quantity of options...

**Comment by erdogant** [comment]
indeed. The chi square and related independence tests is definitely I will start with. However, something that would be even nicer is something like boot.strength() 

as it estimates the strength of each arc as its empirical frequency over a set of networks learned from bootstrap samples. This would also solve one of your earlier questions I guess.

https://search.r-project.org/CRAN/refmans/bnlearn/html/arc.strength.html

**Comment by erdogant** [comment]
Computing significance to determine the edge strength is now implemented! More information can be found [here](https://erdogant.github.io/bnlearn/pages/html/bnlearn.bnlearn.html#bnlearn.bnlearn.independence_test).

Examples can be found in the readme and [here](https://erdogant.github.io/bnlearn/pages/html/Structure%20learning.html#)

Update with:

`pip install -U bnlearn
`

**Comment by PARODBE** [comment]
Uoooo you are brilliant @erdogant !! Thank you for all!

**Comment by erdogant** [comment]
enjoy!
