### ISSUE TITLE
structure_learning.fit() OutEdges broken after 0.3.20 module

### ISSUE THREAD

**Issue by SurfinScott** [erdogant/bnlearn#45]
Hello! Version 0.3.20 works well for a simple DAG inference from a matrix, however 0.3.21 and later the model edges are always empty after fitting.  Attached is a reproduction script.  The example matrix has a set of 4 time series metrics amplitude-ranged 0..1 inclusive. The root of each paired time series amplitude product averaged over time is used as a proxy for pair codependence
[inferTest.py.txt](https://github.com/erdogant/bnlearn/files/7794571/inferTest.py.txt)
.

**Comment by erdogant** [comment]
I could not test on the older version but it seems that BIC does not result in any causations anymore. If you use another score type, it does result in edges. Can you check the underneath example:

```
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import bnlearn as bn
import pandas

model_cols = ['thing1', 'thing2', 'thing3', 'thing4']
model_obs = np.transpose(np.array([
    [0.01, 0.1, 0.2, 0.3, 0.4, 0.5],  # thing1 metrics (6 samples over time)
    [0.5, 0.7, 0.6, 0.3, 0.2, 0.8],  # thing2 metrics
    [0.3, 0.3, 0.2, 0.7, 0.1, 0.4],  # thing3 metrics
    [0.9, 0.8, 0.2, 0.6, 0.7, 0.1]  # thing4 metrics
]))
print(model_obs)

C = len(model_cols)
assert(np.shape(model_obs)[1] == C)  # square!
# brute-force C^2 joint covaried amplitude probabilities
# of 0..1 range-normal metrics pairs
jcvp = np.zeros((C, C))
for cX in range(C):
    for cY in range(C):
        jcvp[cX, cY] = np.sqrt(np.mean(model_obs[cX] * model_obs[cY]))
df = pandas.DataFrame(jcvp, columns=model_cols)
df.head()
print(df)
print("")

# df = bn.import_example('sprinkler')
# model = bn.structure_learning.fit(df, methodtype='hc', scoretype='bic')
model = bn.structure_learning.fit(df, methodtype='hc', scoretype='k2')

edge_properties = bn.get_edge_properties(model, color='#FF0000')
node_properties = bn.get_node_properties(model, node_color='#FFFFFF')
params_static={'layout': 'circular_layout', 'arrowstyle': '->', 'arrowsize': 20, 'edge_alpha': 0.65, 'font_size': 14, 'font_family': 'sans-serif', 'font_color': 'b'}
bn.plot(model, node_properties=node_properties, edge_properties=edge_properties, params_static=params_static)


```

**Comment by SurfinScott** [comment]
Thank you for the quick reply - yes k2 works fine on 0.4.11.

Kind regards,
Scott

{ name     : "Scott Kurowski",
  title    : "Staff Engineer",
  email    : ***@***.***",
  location : "San Diego, CA" }

Think Big, Go Far | Make It Matter | Build Together | Be Intellectually
Honest | Own What You Do

**Comment by erdogant** [comment]
Great!
