### ISSUE TITLE
Interactive plot not show bn.plot

### ISSUE THREAD

**Issue by duducrail** [erdogant/bnlearn#47]
Hi, I'm having problem to visualise interactive plots.
I have installed pyvis and I did a test with Game of thrones example from pyvis using Network and works fine.
But with bnlearn I got this:

Python 3.7.7 on Mac

![interactive](https://user-images.githubusercontent.com/73850995/151401291-46bf02ea-b11a-4f67-9540-90abf25cee39.jpg)
![5027F6F9-68DD-47CB-B3F9-DFCA2A286663](https://user-images.githubusercontent.com/73850995/151401756-d376a98e-7ae2-408f-a264-a31fb25ecdeb.png)

**Comment by erdogant** [comment]
Does it work when you use the [Colab example](https://colab.research.google.com/github/erdogant/bnlearn/blob/master/notebooks/bnlearn.ipynb)?

Something else that you can try is if you use, jupyter notebook, try to set the notebook parameter to True
bn.plot(model, interactive=True, params_interactive = { 'notebook':True})

**Comment by duducrail** [comment]
Thanks for your fast response.
bn.plot(model, interactive=True, params_interactive = { 'notebook':True}) -  didn't work.
And when I tried to open Colab example gave this issues:

![85CD5D0D-E8DD-4D4E-8ADE-7F0EDB1BD549](https://user-images.githubusercontent.com/73850995/151539102-8dbdc2eb-9927-43c7-a388-38d3e310d8fa.png)


![01921211-B139-4FAB-BF83-21CA012DB4C0](https://user-images.githubusercontent.com/73850995/151539150-5e49d149-e6c4-4c6e-b3aa-ed4df2cabfed.png)

**Comment by erdogant** [comment]
I fixed the issue. Can you try again the [colab](https://colab.research.google.com/github/erdogant/bnlearn/blob/master/notebooks/bnlearn.ipynb)

**Comment by duducrail** [comment]
Hi erdogant, sorry to bother again. But the colab example also didn't work. I'm putting the Game of thrones example that is working.

![716DD893-0AFD-48BB-8DB6-A3047FDF8D83](https://user-images.githubusercontent.com/73850995/151561797-d89b3959-1555-42e4-bc4b-a6a616793ffc.png)


![A0026DFB-58C0-4F9A-8D75-86E6B5B81BC0](https://user-images.githubusercontent.com/73850995/151561867-a9dca62c-b1c8-4dbe-aa57-b67c28b0e3bc.png)

With colab example I got this blank on the interactive plot. Maybe is something on my side. I'll try to investigate more as well. Thanks for now. If you have any more things I can try, please I'd like to hear.

![AA03FCDC-D7B0-4997-85B0-FEBBD02E77D4](https://user-images.githubusercontent.com/73850995/151562201-08e95636-04e0-4e2d-b843-3bafca654a80.png)

**Comment by erdogant** [comment]
thanks, this is example is useful, I will look into it!

**Comment by erdogant** [comment]
I compared your working code with that in bnlearn and I created a few changed that -may-can-help but Im not sure because I can not make a not-working-version at my machine. 

I created a small example, can you try whether this works?

```
# Example dataset
source=['Cloudy','Cloudy','Sprinkler','Rain']
target=['Sprinkler','Rain','Wet_Grass','Wet_Grass']
weights=[1,2,1,3]

# Convert into sparse datamatrix
df = bn.vec2df(source, target, weights=weights)
# Make DAG
DAG = bn.make_DAG(list(zip(source, target)), verbose=0)
# Make plot
bn.plot(DAG, interactive=True)

```

**Comment by erdogant** [comment]
Re-open if this still is an issue.

**Comment by duducrail** [comment]
Hi, sorry for the late reply. Still didn't work.
Got this blank plot.

![9AFBA8CC-742B-4314-8AB9-96C4751BD9EE](https://user-images.githubusercontent.com/73850995/161800912-7ee247a7-6818-424e-9f42-4af5b486527b.png)

**Comment by erdogant** [comment]
I added the cdn resources, which can now be changed depending whether jupyter notebook/ Colab etc.
It fixes the issues of blank plots in colab and on my machine.

**Comment by erdogant** [comment]
I am closing this issue. Reopen if it does not work.
