### ISSUE TITLE
How to perform structure learning on prior defined sets of variables?

### ISSUE THREAD

**Issue by wanglu2014** [erdogant/bnlearn#48]
Our goal train a _pyramid_ like bayesian network . 
For example, the root node is Death. The second level nodes of model shall be automaticly selected from Age, Disease and Gender. And the  third level node of model shall be selected from Income and City.

  Death
/                \
Age—Disease
               /
               Income
I known Structural Equation Models can do it. However, since I am a newbie to bnlearn, could you kindly suggest how bnlearn do it.

**Comment by erdogant** [comment]
Try the Chow-liu and TAN methods, which are both Tree search-based approaches. It requires setting a root_node and/or class_node. Details and examples can be found in the [sphinx pages](https://erdogant.github.io/bnlearn/pages/html/Structure%20learning.html#chow-liu).

Perhaps the whitelist/blacklist can also be useful, [see here](https://erdogant.github.io/bnlearn/pages/html/whitelist_blacklist.html?highlight=black_list).

**Comment by erdogant** [comment]
Reopen if you have other related questions.

**Comment by wanglu2014** [comment]
> Reopen if you have other related questions.

Thank you for your kindly reply. I will reopen it when needed.
