### ISSUE TITLE
how to get the adjacent matrix?

### ISSUE THREAD

**Issue by jzhanghzau** [erdogant/bnlearn#5]
I am really appreciate this project,thanks.I want to ask you that could you  provide us a interface that could get the adjacent matrix after getting the model.
thanks!

**Comment by erdogant** [comment]
Thank you!
I added the adjmat to all functionalities which makes the outputs more consistent.
I also added some documentation about adjacency matrices: https://erdogant.github.io/bnlearn/pages/html/Adjacency%20matrix.html

I hope this solves your issue.
