### ISSUE TITLE
Independence test plot

### ISSUE THREAD

**Issue by PARODBE** [erdogant/bnlearn#50]
Hi,

One question, when you use the independence test function and after you make a plot the bold arrows also are representing some relationships >0.5. How could I choose the intervals of pvalues? For example: More bold for p<0.01, less intensity for p<0.05, and normal arrows not bold.

And another question, when you put in the bn.plot function G['pos'], what is the difference if you don't put it?

Thanks!

**Comment by erdogant** [comment]
The best way is to transform your P-values using `-log10(P)`. After the transformation step, you can easily scale it further as you wish. The `pos` parameter keeps the node locations exactly the same. This makes a comparison more easier.

**Comment by PARODBE** [comment]
Like this:

![image](https://user-images.githubusercontent.com/62376157/155711901-9ae33c18-5365-4479-87de-c444232a7bd0.png)

But I can see a scale parameter, but if i put something like [1.4,1.5], i obtain all in arrow. How could I put correctly the intervals?

**Comment by erdogant** [comment]
it is also possible, and maybe even easier, to use the chi2 statistics for the thickness of the edge. Can you elaborate a bit more what you mean with setting the intervals?

**Comment by PARODBE** [comment]
Yes sure. For example, the relationTarget-OATP1B1 has a pvalue of 0.03 which is <0.05 then for the relations with pvalue<0.05 (in my example there are only one) to stablish a specific thickness, if we had relations with p<0.01 a higher thickness than 0.05. In fact, it is the same that now but I want control based on pvalue generally since <0.01 to 0.01, 0.05, >0.05. Or also for example significative(<0.05), not significative (>0.05).

**Comment by erdogant** [comment]
You mean that the differences between the values are too small to see in the edge-thickness, right? The easiest way to emphasize stronger P-values is by multiplying the -log10(P) with factor 10 or a non-linear scaling. P-values with >0.05 can be set at the minimum visible line thickness. P-values that are beyond machine precision (0), can be set at the edge-thinkness of the strongest P-value plus a bit more. 

To edge-thickness is a way to emphasize certain relationships, and for the exact P-value, people can look it up in the table.
