### ISSUE TITLE
Does Inference/Predict model support parallelism during computing?

### ISSUE THREAD

**Issue by Mikcy1595** [erdogant/bnlearn#53]
Hi erdogant,

It is a great library. Firstly, thanks for your efforts. I was using bn model to predict a large dataset. I found the time consuming is massive and while the CPU usage is quite low. The bnlearn library does not have inbuilt parallelism function, alternatively I used library 'joblib' to enable all the cores. But it seems not really working. Is it able to intergrate the parallelism computing in bnlearn library? Do you have any suggestions that might help?

Thank you !

![image](https://user-images.githubusercontent.com/91182526/163682349-c136ca80-37c9-48c2-bf01-c6c61bfd4950.png)
![image](https://user-images.githubusercontent.com/91182526/163682360-d787706c-9c7c-4c60-bec7-906091e455aa.png)

**Comment by erdogant** [comment]
I did not try this before but I am going to look into this.

**Comment by erdogant** [comment]
You are right, this function is quite slow as it runs in a simple for-loop. Using your approach will not work for this function.
The following for-loop needs to be parallelized. If you have any suggestions, let me know.

  for i in tqdm(range(dfU.shape[0])):
      # Get input data and create a dict.
      evidence = dfU.iloc[i, :].to_dict()
      # Do the inference.
      query = bnlearn.inference.fit(model, variables=variables, evidence=evidence, to_df=False, verbose=0)
      # Find original location of the input data.
      loc = np.sum((dfX==dfU.iloc[i, :]).values, axis=1)==dfU.shape[1]
      # Store inference
      P[loc] = _get_prob(query, method=method)

**Comment by erdogant** [comment]
Did you also try the `numba` package? 
It requires to import a decorator `jit` and it will do all the rest.

from numba import njit
```
# @njit
def predict(model, df, variables, to_df=True, method='max', verbose=3):
...

```

**Comment by erdogant** [comment]
There are multiple parallel functions in Bnlearn now by setting n_jobs.
