### ISSUE TITLE
Reading .RDA or .RDS files for Asia Graph

### ISSUE THREAD

**Issue by adam2392** [erdogant/bnlearn#55]
Hi

In https://www.bnlearn.com/bnrepository/discrete-small.html#asia, the .rds and .rda files contain the conditional probability table. I was wondering if it is possible to read in those files data using the Python bnlearn?

Thanks!

**Comment by erdogant** [comment]
Sure. See [here](https://erdogant.github.io/bnlearn/pages/html/Example%20Datasets.html) in the docs.

It is as easy as this:

```
# Load asia DAG
df = bn.import_example(data='asia')
# Structure learning of sampled dataset
model = bn.structure_learning.fit(df)
# Make plot
G = bn.plot(model)

```

**Comment by erdogant** [comment]
I am closing this issue. Please re-open if needed.
