### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by samanemami** [erdogant/bnlearn#56]
Thank you very much for developing this amazing repository.

I encountered an issue when reviewing the documentation, which was the example part. In this section, there are lots of bold examples with in-built datasets and data frames, but I could not find any example related to another dataset (assuming a local dataset).
Also, I could not find documentation for the class parameters and attributes.

Thank you again for your efforts in sharing the practical repository.

**Comment by erdogant** [comment]
Thanks! Class parameters and attributes are in the docs but indeed, maybe a bit hidden. I changed the docs and added the section **Parameters and attributes** for clarity. It should be easy to find now. An example to start with your own datasets can be found in [this section](https://erdogant.github.io/bnlearn/pages/html/Examples.html) with the titanic dataset or [here](https://erdogant.github.io/bnlearn/pages/html/UseCases.html) another one.

**Comment by samanemami** [comment]
I appreciate your consideration @erdogant
