### ISSUE TITLE
find the result of the query

### ISSUE THREAD

**Issue by samanemami** [erdogant/bnlearn#57]
Is the only strategy in the library to find the result of the query in the joint probability, variable elimination?
Are there other approaches such as Gibbs as well?

**Comment by erdogant** [comment]
Correct. At the moment only variable elimination is available. However, I just added Gibbs as a new sampling method.
See more information at the [documentation pages](https://erdogant.github.io/bnlearn/pages/html/Sampling.html#gibbs-sampling).

bnlearn version should be >= '0.7.4'

**Comment by samanemami** [comment]
Thank you @erdogant
