### ISSUE TITLE
fit() got an unexpected keyword argument 'evidance'

### ISSUE THREAD

**Issue by samanemami** [erdogant/bnlearn#58]
I am trying to reproduce the Inference example by making DAG with the following method;
```Python
model = bn.structure_learning.fit(df, methodtype='hc', scoretype='bic')
DAG = bn.make_DAG(model)
q1 =bn.inference.fit(DAG, variables=['3'], evidance={'1':0})
```

But I receive the following TypeError

```log
TypeError: fit() got an unexpected keyword argument 'evidance'
```

I know that it comes from the DAG, but DAG is a dictionary and it is based on the standard of the example in the documentation.

Could you help me with this, please?

**Comment by erdogant** [comment]
Seems like a typo: try `evidence` instead of `evidance`

If this example comes from the from documentation pages, I need to fix the typo.

**Comment by samanemami** [comment]
> Seems like a typo: try `evidence` instead of `evidance`
> 
> If this example comes from the from documentation pages, I need to fix the typo.

The example of the documentation works perfectly.
But when I use `structure_learning.fit()` method to construct a DAG with `make_DAG()`, it returns an error in `inference()`, but if I manually construct the edges in the dictionary, it works fine.

**Comment by erdogant** [comment]
Ok! I will look at this!

**Comment by samanemami** [comment]
> Ok! I will look at this!

Thank you so much

**Comment by samanemami** [comment]
Thank you @erdogant 
I managed to fix the problem. It was coming from the data frame. I am using uchar8 as the data type for the model input.
But I can not make the predict method work. It gives me the following error;

![image](https://user-images.githubusercontent.com/54855771/183255839-1544d278-de03-4948-b333-39188941fecd.png)

**Comment by erdogant** [comment]
Did you try to update to the latest version?
It seems look an issue that may have fixed the other day.

Try first:

`pip install -U bnlearn`

**Comment by samanemami** [comment]
It is not working with the last version.
If you send me the kaggle user, I can give you access to the problem.
Thank you
