### ISSUE TITLE
Sparse Structure Learning for Massive Datasets

### ISSUE THREAD

**Issue by arainboldt** [erdogant/bnlearn#59]
Hi, 

Great package. I really enjoy using it! 

I'm working on a project with datasets where the number of variables is 3000+ for which a bayesian network would be ideal choice to model the data. Unfortunately, as we all know, structure learning for Bayes Nets is exponential and consequently, unfeasible for such a wide dataset. 

In my research, I've come across this [paper](https://www.biostat.wisc.edu/bmi576/papers/sparse.pdf) which looks very encouraging as a method for addressing the exponential complexity of structure learning. 

Is there a straightforward way to implement the parent constraint method described in the paper using the existing structure learning framework in the package?

Any insights or direction is much appreciated

Thanks!

Andrew

**Comment by erdogant** [comment]
Thanks for your question. Did you already find a solution for this?
