### ISSUE TITLE
Issue with the sampling method -  AttributeError: type object 'object' has no attribute 'dtype'

### ISSUE THREAD

**Issue by agcgit** [erdogant/bnlearn#62]
The following code  result in error

I'm using python 3.8

# Import library
import bnlearn as bn
print(bn.__version__)
![image](https://user-images.githubusercontent.com/43915232/201036283-b1c861a6-06aa-4bb9-b0ea-3d0a6481951a.png)

model = bn.import_DAG('sprinkler', CPD=True)
df = bn.sampling(model, n=1000, methodtype='bayes')

df.head()

![image](https://user-images.githubusercontent.com/43915232/201036561-7def1820-c149-4ee6-a2a4-2e1b9da7400c.png)

**Comment by erdogant** [comment]
Can you check the version of pgmpy that you are using?
```
import pgmpy
pgmpy.__version__

```

I use version '0.1.18' which does not give this error.
If you have a older version, try to update first with: `pip install -U pgmpy`

**Comment by goumane84** [comment]
my version of pgmpy is '0.1.20', I tried to to downgrade to 0.1.18 but it still giving giving the same error

**Comment by erdogant** [comment]
If you try the colab notebook example, does it also throw an error?

**Comment by goumane84** [comment]
error in colab notebook

-----
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-706f18ff854b>](https://localhost:8080/#) in <module>
      1 model = bn.import_DAG('sprinkler', CPD=True)
----> 2 df = bn.sampling(model, n=10000,methodtype='bayes')
      3 

TypeError: sampling() got an unexpected keyword argument 'methodtype'

however if I remove the methodtype argument its working.

**Comment by erdogant** [comment]
It seems that many packages require Python >3.8 or higher. Colab runs in python 3.7 (I did not realize this) and therefore older versions of packages are installed (including bnlearn). But try to create an environment with >python3.8, (3.10 or so), this will likely solve your issue.

**Comment by erdogant** [comment]
I am closing this issue. Please re-open if required.
