### ISSUE TITLE
Save network plot as image

### ISSUE THREAD

**Issue by sbhadana** [erdogant/bnlearn#65]
After creating the network, bn.plot(model) displays the network, but how to save it as image without using an IDE.
q = bn.plot(model) return a dict not a fig object. 

![image](https://user-images.githubusercontent.com/50580839/204768731-02918b08-0137-4f0e-bee8-d19db2850fc4.png)

Is there any functionality which I am missing?

**Comment by erdogant** [comment]
Good point. This was not returned but now it is!

Update to the latest version with:
`pip install -U bnlearn`

Example:
```
import bnlearn as bn
model = bn.import_DAG('sprinkler', CPD=True)
df = bn.sampling(model, n=1000, methodtype='bayes')
fig = bn.plot(model)
fig['ax']

# Toggle with the visible status
fig = bn.plot(model, params_static={'visible': True})
```
