### ISSUE TITLE
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'

### ISSUE THREAD

**Issue by dcooper46** [erdogant/bnlearn#66]
scikt-learn team is removing the `sklearn` package from PyPI and currently causes a failure when installing packages with `sklearn` in their `requirements.txt` .

**Comment by erdogant** [comment]
Thanks for notifying! I changed sklearn into scikit-learn in both setup and requirements file and released a new version.
Update to the latest version with `pip install -U bnlearn`

**Comment by dcooper46** [comment]
Awesome! Thank you.  Great package btw.
