### ISSUE TITLE
bn.plot

### ISSUE THREAD

**Issue by natank1** [erdogant/bnlearn#68]
For some reasons, bn.plot  doesnt work it creates alerets but not the graph

**Comment by erdogant** [comment]
I just released an update to fix the colab interactive plots.

But for the static plots, does this work for you?
```
import bnlearn as bn
model = bn.import_DAG('sprinkler', CPD=True)
df = bn.sampling(model, n=1000, methodtype='bayes')
fig = bn.plot(model, params_static={'visible': True})

```
Maybe try to force to show the plot
`fig['ax'].show()
`

**Comment by natank1** [comment]
That's the message
Traceback (most recent call last):
  File "/Users/natank/checkpoint/IOT_PROJECT/deepcover/training/rr5.py",
line 3, in <module>
    df = bn.sampling(model, n=1000, methodtype='bayes')
TypeError: sampling() got an unexpected keyword argument 'methodtype'

**Comment by erdogant** [comment]
can you check the version?
```
import bnlearn
bnlearn__version__
```

**Comment by natank1** [comment]
0.4.2 (I downgraded)

**Comment by natank1** [comment]
When I upgraded  I got this

0.7.11
[bnlearn] >Import <sprinkler>
[bnlearn] >Check whether CPDs sum up to one.
[bnlearn] >Check whether CPDs associated with the nodes are consistent: True
[bnlearn] >Set node properties.
[bnlearn] >Set edge properties.
[bnlearn] >Plot based on Bayesian model

With no grpah

**Comment by erdogant** [comment]
There is one newer update.
force install from pypi:
`pip install -U bnlearn`

did you try this:
```
from matplotlib.pyplot import plot, draw
draw()
```
or
`fig['ax'].show() `

**Comment by natank1** [comment]
It opens and instantaneously close. Namely, i see on the bar the sign of a
plot appears and disappears before the graph comes

**Comment by natank1** [comment]
If I run in debug :

print(bn.__version__)
model = bn.import_DAG('sprinkler', CPD=True)
df = bn.sampling(model, n=1000, methodtype='bayes')
fig = bn.plot(model, params_static={'visible': True})
print ("hi")


and put the toggle on the last print Ican see the graph but it then
removes it perhaps it is something about my pycharm (akthough I dont
have these issues in regular matplotlib)

**Comment by erdogant** [comment]
Can you try this: `plt.show(block=False)`

**Comment by natank1** [comment]
plot ? fix.plot? pyplot.plot?

**Comment by erdogant** [comment]
Did you try to change the backend of matplotlb? See [this](https://stackoverflow.com/questions/7534453/matplotlib-does-not-show-my-plot-although-i-call-pyplot-show) thread on stack.

```
import matplotlib
matplotlib.use("gtk")

```
or maybe `%matplotlib inline`

**Comment by natank1** [comment]
ValueError: 'gtk' is not a valid value for backend; supported values are

Different values gave different messages . which version of matplotlib do I
have to use? which netwrokx?

**Comment by erdogant** [comment]
I use the latest one.

**Comment by natank1** [comment]
Upgraded to 3.6.2 , it still doesnt know gtk

**Comment by erdogant** [comment]
What do you have?

```
import matplotlib.rcsetup as rcsetup
print(rcsetup.all_backends)
```

**Comment by natank1** [comment]
['GTK3Agg', 'GTK3Cairo', 'GTK4Agg', 'GTK4Cairo', 'MacOSX', 'nbAgg',
'QtAgg', 'QtCairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg',
'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg',
'template']

**Comment by erdogant** [comment]
You can try to set it to: `matplotlib.use("GTK3Agg")
`
You can also try this:
```
%matplotib inline
%pylab inline

```

**Comment by erdogant** [comment]
Otherwise, I recommend creating a new environment. Maybe something did accidentally break.

**Comment by erdogant** [comment]
There was also a thread about empty figures in matplotlib: https://github.com/matplotlib/matplotlib/issues/12074
Maybe it is also helpful to you.

**Comment by oliver3** [comment]
Maybe this will be fixed after https://github.com/erdogant/bnlearn/pull/71

**Comment by erdogant** [comment]
New version of Bnlearn is released that is related to this one too. See #103

**Comment by erdogant** [comment]
Closing this one as it should be fixed with the latest update. Re-open if required!
