### ISSUE TITLE
Input variable ordering.

### ISSUE THREAD

**Issue by sidjr2** [erdogant/bnlearn#69]
Hey, how are you? 
I'm doing a research with HC and K2 algorithm. However, I'm little confused about how the reading of the file is done (dataset). It is done in order of writing or randomly?

**Comment by erdogant** [comment]
Can you maybe demonstrate your point with an example?

**Comment by sidjr2** [comment]
My problem is discover when I create the dataframe, what  is the process used to read the data. If using a random draw, how and when this sortition is made. I would like to optimize the algorithm for unknown data and I need to know how the reading process is made and how can I optimize it.

**Comment by erdogant** [comment]
Some methods that are used, such as HC and K2 rely on the pgmpy package. The best manner to exactly figure this out, is to step-wise debug through the code. Spyder can be helpful for debugging.
