### ISSUE TITLE
Structured Learning Issue

### ISSUE THREAD

**Issue by Mr-Styles** [erdogant/bnlearn#80]
Does not matter how I edit the data I'm using, running structured learning produces nothing; just with statistical noise some structure would have emerged.

**Comment by erdogant** [comment]
Can you demonstrate your issue with an example?[Here](https://erdogant.github.io/bnlearn/pages/html/Examples.html#structure-learning)  are the docs with examples that should work.

**Comment by Mr-Styles** [comment]
I used your introduction examples:

model_hc_bic  = bn.structure_learning.fit(train_df, methodtype='hc', scoretype='bic')
# adjacency matrix:
model_hc_bic['adjmat']
# plot model
G = bn.plot(model_hc_bic)

Result:
Ajacemcy all FALSE.
[bnlearn] >Computing best DAG using [hc]
[bnlearn] >Set scoring type at [bic]
[bnlearn] >Compute structure scores for model comparison (higher is better).
[bnlearn]> Nothing to plot because no edges are present between nodes. 

While not the same package, the R version of BNLearn works on this data.

**Comment by erdogant** [comment]
Which of the training examples is train_df?

**Comment by Mr-Styles** [comment]
> Which of the training examples is train_df?

My own data; HillClimbSearch using pgmpy provides a structure as does the unrelated R library.

**Comment by erdogant** [comment]
I am closing this issue. When you have a working example to demonstrate this issue, feel free to re-open it. At this point, there is nothing I can do.
