### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by vin2015-edem** [erdogant/bnlearn#82]
I am trying to install it in Kaggle.

`!pip install bnlearn`
or
`!pip install git+https://github.com/erdogant/bnlearn`

But it gives me an error
`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/numpy-1.25.0.dist-info/METADATA'`

Everything worked before (a year ago) - see my example: [Pollen - BN for Paper](https://www.kaggle.com/code/vbmokin/pollen-bn-for-paper/notebook)

**Comment by erdogant** [comment]
Numpy must be of version `numpy>=1.24.1` 
When I check it in Kaggle it has a lower version

```
import numpy
numpy.__version__

```

try to update numpy to the latest version:

`pip install -U numpy
`

**Comment by vin2015-edem** [comment]
![image](https://github.com/erdogant/bnlearn/assets/13628761/76350b90-413a-468d-af2f-b4e8c5c48d5f)

**Comment by erdogant** [comment]
I was able to reproduce the error and created a gif how I could solve the issue. See issue #86  for the solution.
