### ISSUE TITLE
Lowering case of path when importing DAG 

### ISSUE THREAD

**Issue by White-On** [erdogant/bnlearn#83]
Hello. I was wondering why it is necessary to lower the path string when importing the DAG structure. Maybe let the user decide if the path requires such changes would be more suitable.

https://github.com/erdogant/bnlearn/blob/8248e7f75dd7e745c4bcb95ec79923f00c0eb313/bnlearn/bnlearn.py#L1336-L1367

Have a great day and thanks !

**Comment by erdogant** [comment]
Agree. I removed the lowering.

I created a new release and include this change.
update to the newest version with:

`pip install -U bnlearn
`
