### ISSUE TITLE
BUG report:

### ISSUE THREAD

**Issue by ms440** [erdogant/bnlearn#9]
Current code in `https://github.com/erdogant/bnlearn/blob/master/bnlearn/__init__.py#L37-38`:

```
if not version.parse(nx.__version__) > version.parse("2.5"):
    print('[bnlearn] >Error: networkx version should be > 2.5.\nTry to: pip install -U networkx')
```

Proposed fix:

```
if not version.parse(nx.__version__) >= version.parse("2.5"):
    print('[bnlearn] >Error: networkx version should be >= 2.5.\nTry to: pip install -U networkx')
```

Explanation:
`networkx` version currently available at PyPI is 2.5

**Comment by erdogant** [comment]
Thank you for these fixes! Its merged now.

Your other suggestion, for pgmpy version 0.1.12, for the use of PC did fail on the unit tests. I looked deeper into it and noticed that something was changed in the black_list parameter. An error was thrown in the HillClimbSearch of pgmpy at some point for dict "t[1]". For the time being I recommend using pgmpy version to 0.1.11.

**Comment by ms440** [comment]
Yes, you're right - while the replacement to `PC` was just a hack, it did help me for my use case, but nothing more than that. Thank you for the quick check, response, and fix. I'll try to check `pgmpy` 0.1.11 and see if it will help.
