### ISSUE TITLE
Remove d3blocks?

### ISSUE THREAD

**Issue by chrisflatley** [erdogant/bnlearn#99]
The recently d3blocks introduces some problems:

- 1.4.10 causes the version check to fail (at least for me) (bug with 1.4.9 > 1.4.10)
- d3blocks is GPL-3, which makes this library GPL-3 not MIT.
 
I wondered if it's necessary to include d3blocks as a formal dependency?

**Comment by erdogant** [comment]
True. I removed it from the setup/requirements and added it now as a check when using the interactive plot functionality.
